baseURL = "/"
languageCode = "en-us"
paginate = 9
relativeurls = true
summaryLength = "150"
theme = "timer-hugo"
title = "DCAN | Dorset Climate Action Network"

[params]
author = "Dorset CAN"
contactFormAction = "#"
dateFormat = "6 January 2006"
description = "Dorset Climate Alliance Network"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "/uploads/dorset-can-logo-3000px.png"

[[menu.main]]
name = "Our Network"
url = "network"
weight = 3
[[menu.main]]
name = "Join Us"
url = "join"
weight = 6
[[menu.main]]
name = "Projects"
url = "projects"
weight = 5
[[menu.main]]
name = "About Us"
url = "about"
weight = 1
[[menu.main]]
name = "News & Events"
url = "news_events"
weight = 4
[[menu.main]]
name = "Teams"
url = "teams"
weight = 2
